import prcinf_departement
import prcinf_serveur
import prcinf_ordinateur
import prcinf_fournisseur
import prcinf_responsable
import prcinf_brand
import prcinf_peripherique
import prcinf_reseau
import prcinf_salle
import prcinf_serveur
import prcinf_tablet
import prcinf_stock



